### PR TITLE
Grafana support

### PR DESCRIPTION
**Pull request by thouveng**

### CODE REVIEW

**Comment by thouveng** [comment]
This PR is based on #15

**Comment by elemoine** [comment]
The commit message says "Add StackLight dashboards". Is this really the case?

**Comment by elemoine** [comment]
I tested this together with https://github.com/tcpcloud/salt-formula-grafana/pull/4. There is one issue: the InfluxDB datasource is not configured in Grafana, resulting in non-functional dashboards. I'd suggest that we merge what we have and fix the datasource configuration with separate PRs.

Information to developers: if you don't re-apply the `salt` state and just update the salt-formula-grafana repo, manual steps are required. This is what I did:

```
cd /usr/share/salt-formulas/env/_formulas/grafana
git fetch origin pull/4/head
git checkout -b fix-datasource FETCH_HEAD
cp -R _states/* /usr/share/salt-formulas/env/_states/
salt 'mon*' saltutils.refresh_states
```

and then restart `salt-minion` on the monitoring node.

Now apply the `linux` and `grafana` states on the monitoring node:

```
salt 'mon*' state.sls linux,grafana
```

**Comment by elemoine** [comment]
> I guess you mean tcpcloud/salt-formula-grafana#4 and not #15

No, initially this PR was based on https://github.com/Mirantis/mk-lab-salt-model/pull/15, meaning that it included the commits that were in https://github.com/Mirantis/mk-lab-salt-model/pull/15.

**Pull request merged**
