### PR TITLE
Remove dependency on script launch location

### PR DESCRIPTION
**Pull request by obourdon**

### CODE REVIEW

**Comment by simonpasquier** [comment]
if you have time, you could replace backticks by `$(...)`...

**Comment by elemoine** [comment]
> if you have time, you could replace backticks by $(...)...

It seems that the `$()` is the preferred way: http://stackoverflow.com/questions/8941381/what-is-the-difference-between-backticks-and-in-bash-script#8941461.

**Comment by obourdon** [comment]
@simonpasquier @elemoine yes, sorry about this, spent too many years working in an environment where sh was the default shell and not bash ;-)

However please also note that I will need to update this PR to cope with new common functions module introduced in https://github.com/Mirantis/mk-lab-salt-model/pull/198

PLEASE DO NOT MERGE THIS UNTIL THEN

**Comment by obourdon** [comment]
@simonpasquier @elemoine now integrating your comments and can be merged as integrated fully with #198

**Pull request merged**
